"""Authorization Code Flow with PKCE for Solid-OIDC (OIDC-14).

Provides the building blocks for interactive login flows where a user
authenticates via a browser. This complements the client credentials
flow for machine-to-machine auth.

Usage:
    auth_url, verifier, state = start_auth_flow(issuer, client_id, redirect_uri)
    # User visits auth_url in a browser, gets redirected back with ?code=...
    token_data = await exchange_auth_code(token_endpoint, code, redirect_uri, verifier, ...)
"""

from __future__ import annotations

import base64
import hashlib
import logging
import secrets
import urllib.parse
from typing import Any

from people._auth.dpop import DPoPKey
from people._http.tls import enforce_tls

logger = logging.getLogger("people")


def generate_pkce() -> tuple[str, str]:
    """Generate a PKCE code_verifier and code_challenge (S256).

    Returns:
        (code_verifier, code_challenge) tuple.
    """
    code_verifier = secrets.token_urlsafe(64)
    digest = hashlib.sha256(code_verifier.encode("ascii")).digest()
    code_challenge = base64.urlsafe_b64encode(digest).rstrip(b"=").decode("ascii")
    return code_verifier, code_challenge


def start_auth_flow(
    authorization_endpoint: str,
    client_id: str,
    redirect_uri: str,
    *,
    scopes: list[str] | None = None,
) -> tuple[str, str, str]:
    """Build the authorization URL and PKCE parameters.

    Args:
        authorization_endpoint: The OIDC authorization endpoint URL.
        client_id: The client identifier (may be a URL or registered ID).
        redirect_uri: Where the user will be redirected after authentication.
        scopes: OIDC scopes to request. Defaults to ["openid", "webid"].

    Returns:
        A tuple of (authorization_url, code_verifier, state).
        The caller must:
        1. Open authorization_url in a browser
        2. Capture the ?code= parameter from the redirect
        3. Call exchange_auth_code() with the code and code_verifier
    """
    if scopes is None:
        scopes = ["openid", "webid"]

    code_verifier, code_challenge = generate_pkce()
    state = secrets.token_urlsafe(32)

    params = {
        "response_type": "code",
        "client_id": client_id,
        "redirect_uri": redirect_uri,
        "scope": " ".join(scopes),
        "state": state,
        "code_challenge": code_challenge,
        "code_challenge_method": "S256",
    }

    auth_url = f"{authorization_endpoint}?{urllib.parse.urlencode(params)}"
    logger.debug("Auth flow started: %s", auth_url)

    return auth_url, code_verifier, state


async def exchange_auth_code(
    token_endpoint: str,
    code: str,
    redirect_uri: str,
    code_verifier: str,
    client_id: str,
    dpop_key: DPoPKey,
) -> dict[str, Any]:
    """Exchange an authorization code for tokens with DPoP (OIDC-14).

    Args:
        token_endpoint: The OIDC token endpoint URL.
        code: The authorization code received from the callback.
        redirect_uri: The same redirect_uri used in the authorization request.
        code_verifier: The PKCE code_verifier generated by start_auth_flow().
        client_id: The client identifier.
        dpop_key: The DPoP key pair for proof generation.

    Returns:
        The token response dict containing access_token, id_token, etc.
    """
    import httpx

    enforce_tls(token_endpoint)

    body = urllib.parse.urlencode({
        "grant_type": "authorization_code",
        "code": code,
        "redirect_uri": redirect_uri,
        "client_id": client_id,
        "code_verifier": code_verifier,
    })

    headers = {"Content-Type": "application/x-www-form-urlencoded"}

    async with httpx.AsyncClient() as client:
        # First attempt with DPoP proof
        dpop_proof = dpop_key.sign_proof("POST", token_endpoint)
        resp = await client.post(
            token_endpoint,
            headers={**headers, "DPoP": dpop_proof},
            content=body,
        )

        # Handle DPoP-Nonce requirement
        if resp.status_code in (400, 401):
            nonce = resp.headers.get("dpop-nonce") or resp.headers.get("DPoP-Nonce")
            if nonce:
                dpop_proof = dpop_key.sign_proof("POST", token_endpoint, nonce=nonce)
                resp = await client.post(
                    token_endpoint,
                    headers={**headers, "DPoP": dpop_proof},
                    content=body,
                )

        resp.raise_for_status()
        result: dict[str, Any] = resp.json()
        return result
